name: Lint Code Base
on:
  push:
    #branches-ignore:
    #  - 'master'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 
            pip install -r requirements.txt
        - uses: docker://github/super-linter:v2.1.0
