---
name: Lint Code Base
permissions:
  contents: write
on:
  push:
    #branches-ignore:
    #  - 'master'
jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 
          pip install -r requirements.txt
      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH_EXEC: false
          # Temp disable
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_YAML_PRETTIER: false
